sculpin:
  permalink: pretty
sculpin_theme:
  theme: app/holaluz
sculpin_content_types:
  posts:
    enabled: false
sculpin_twig:
  source_view_paths: ['_views', '_layouts', '_partials', '_includes', '_blocks']
